### ISSUE TITLE
Add parser for Free/Fayn food

### ISSUE THREAD

**Issue by mrshu** [hladny-matfyzak/py-hladny-matfyzak#2]
It seems that free/fayn food now finally has a website (www.freefood.sk/). Moreover, it seems that the menu for the current week is listed there too (http://freefood.sk/menu/).

Therefore, I think this module should have a way of parsing that menu and putting it into accessible format (the same one as in `venza.py`, if possible).

**Comment by tWido** [comment]
Working on it

**Comment by tWido** [comment]
Aaaaand it's done
